HW 26.2 init commit
SetMyDream/JV_MA_InternetShop_Vorobiov pull request #10
Opened 2020-09-14 01:34 UTC by SetMyDream

2020-09-14 02:34 UTC, Vosker reviewed
Норм, пофикси заказы и web.xml

2020-09-14 02:34 UTC, Vosker commented on src/main/java/com/internet/shop/controllers/orders/OrderAdminController.java
> +}
empty line here and almost everywhere)

2020-09-14 02:34 UTC, Vosker commented on src/main/webapp/WEB-INF/views/products/all.jsp
>  <a href="${pageContext.request.contextPath}/shoppingCarts/products">View your cart</a>
32 строка. Тут не должно быть функционала добавления продукта, так как это страница только для юзера(покупка-ок, добавление нового продукта не ок).

2020-09-14 02:34 UTC, Vosker commented on src/main/webapp/WEB-INF/views/orders/user.jsp
> +    <c:forEach var="product" items="${order.products}">
Тут 2 forEach, из-за этого дублируются дважды заказы)

2020-09-14 02:34 UTC, Vosker commented on src/main/webapp/WEB-INF/views/orders/admin.jsp
> +                /orders/delete?id=${order.id}">Delete</a>
Не работает функционал этих ссылок. Из того что я заметил, у тебя в web.xml нету сервлета+мапинга для них хоть контроллеры есть ¯¯\_( ͡° ͜ʖ ͡°)_/¯

2020-09-14 06:49 UTC, SetMyDream commented on src/main/webapp/WEB-INF/views/orders/admin.jsp
> +                /orders/delete?id=${order.id}">Delete</a>
Работает, не сомневайся, я июзал аннотацию @WebServlet()

2020-09-14 07:28 UTC, SetMyDream commented on src/main/webapp/WEB-INF/views/products/all.jsp
>  <a href="${pageContext.request.contextPath}/shoppingCarts/products">View your cart</a>
спасибо, ты прав

2020-09-14 07:36 UTC, SetMyDream commented on src/main/webapp/WEB-INF/views/orders/user.jsp
> +    <c:forEach var="product" items="${order.products}">
Тут ты и прав и не прав: заказа действительно два, но это происходит на уровне Checkout... собстветнно, судя по тому, что я выводил, функция создаёт всегда 2 запроса, что я и пытался пофиксить пол ночи))
а тут два цыкла потому что у одного пользователя может быть много заказов, и я вывожу их все)

2020-09-14 11:09 UTC, KseniiaMakarova requested changes
you are merging your changes into the previous branch - this is wrong
after this homework you should create a PR with all changes made from the start and merge it into `master` branch

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/orders/OrderAdminController.java
> +public class OrderAdminController extends HttpServlet {
```suggestion
@WebServlet("/orders")
public class ShowOrdersController extends HttpServlet {
```

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/orders/OrderDetailController.java
> +        req.setAttribute("products", products);
can we just set `order` as attribute?

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/orders/OrderUserController.java
> +public class OrderUserController extends HttpServlet {
```suggestion
@WebServlet("/user/orders")
public class ShowUserOrdersController extends HttpServlet {
```

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/orders/OrderUserController.java
> +        System.out.println(orderService.getUserOrders(USER_ID));
let's remove this line

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/orders/OrdersDeleteController.java
> +public class OrdersDeleteController extends HttpServlet {
```suggestion
public class DeleteOrderController extends HttpServlet {
```

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/orders/OrdersDeleteController.java
> +        String userId = req.getParameter("id");
userId or orderId?

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/products/AdminProductController.java
> +public class AdminProductController extends HttpServlet {
```suggestion
@WebServlet("/products/manage")
public class ManageProductsController extends HttpServlet {
```

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/products/DeleteProductsController.java
> +        String userId = req.getParameter("id");
userId or productId?

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/products/DeleteProductsController.java
> +        resp.sendRedirect(req.getContextPath() + "/products/admin");
also after adding a new product to storage, we should also redirect to `req.getContextPath() + "/products/admin"`

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/shopcarts/CheckoutController.java
> +@WebServlet("/shoppingCarts/products/checkout")
```suggestion
@WebServlet("/shopping-cart/products/checkout")
```

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/shoppingCarts/products/remove</url-pattern>
```suggestion
        <url-pattern>/shopping-cart/products/remove</url-pattern>
```

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/shopcarts/RemoveProductFromShoppingCartController.java
> +public class RemoveProductFromShoppingCartController extends HttpServlet {
let's use @WebServlet annotation with all our controllers?

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/shopcarts/RemoveProductFromShoppingCartController.java
> +        shoppingCartService.deleteProduct(shoppingCartService.get(USER_ID), productService.get(id));
I think the method in shoppingCartService is wrong

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/shopcarts/RemoveProductFromShoppingCartController.java
> +        resp.sendRedirect(req.getContextPath() + "/shoppingCarts/products");
```suggestion
        resp.sendRedirect(req.getContextPath() + "/shopping-cart/products");
```

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/index.jsp
> +<br> <a href="${pageContext.request.contextPath}/injectData">Go to injector</a> </br>
```suggestion
<br> <a href="${pageContext.request.contextPath}/inject">Go to injector</a> </br>
```
or `inject-data`
let's not use upper case in URL

2020-09-14 11:09 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/orders/user.jsp
> +                /orders/details?id=${order.id}">Details</a>
maybe let's show details after clicking this button and remove the details from here?

2020-09-14 13:45 UTC, SetMyDream commented on src/main/java/com/internet/shop/controllers/shopcarts/RemoveProductFromShoppingCartController.java
> +        shoppingCartService.deleteProduct(shoppingCartService.get(USER_ID), productService.get(id));
What`s wrong with it?

2020-09-14 17:33 UTC, KseniiaMakarova requested changes

2020-09-14 17:33 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/orders/DeleteOrderController.java
> +        resp.sendRedirect(req.getContextPath() + "/orders/admin");
```suggestion
        resp.sendRedirect(req.getContextPath() + "/orders");
```
we need to update this after we changed servlet mapping

2020-09-14 17:33 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/orders/OrderDetailController.java
> +        System.out.println(orderService.getUserOrders(1L));
let's remove this

2020-09-14 17:33 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/orders/OrderDetailController.java
> +        req.setAttribute("products", products);
let's pass the whole order as the attribute to jsp
we will take everything we need in the jsp

2020-09-14 17:33 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/products/DeleteProductsController.java
> +        resp.sendRedirect(req.getContextPath() + "/products/admin");
```suggestion
        resp.sendRedirect(req.getContextPath() + "/products/manage");
```

2020-09-14 17:33 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/shopcarts/CheckoutController.java
> +        resp.sendRedirect(req.getContextPath() + "/orders");
```suggestion
        resp.sendRedirect(req.getContextPath() + "/user/orders");
```

2020-09-14 17:33 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/products/all.jsp
> +<br/>
we don't want the user to see those pages

2020-09-14 17:33 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/products/manage.jsp
> +    <title>Admin</title>
add informative title please

2020-09-14 17:33 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/users/orders.jsp
> +    <title>Your Oder</title>
```suggestion
    <title>Your Order</title>
```

2020-09-15 04:09 UTC, KseniiaMakarova approved these changes

2020-09-15 06:23 UTC, merged